const data = [
    {   
        id: 1,
        name: 'Jennifer',
        img: '../../assets/images/pets-jennifer.png',
        type: 'dog',
        breed: 'Labrador',
        description: 'Jennifer is a sweet 2 months old Labrador that is patiently waiting to find a new forever home. This girl really enjoys being able to go outside to run and play, but won\'t hesitate to play up a storm in the house if she has all of her favorite toys.',
        age: '2 months',
        inoculations: ['none'],
        diseases: ['none'],
        parasites: ['none'],
      },
      {   
        id: 2,
        name: 'Katrine',
        img: '../../assets/images/pets-katrine.png',
        type: 'dog',
        breed: 'Labrador',
        description: 'Jennifer is a sweet 2 months old Labrador that is patiently waiting to find a new forever home. This girl really enjoys being able to go outside to run and play, but won\'t hesitate to play up a storm in the house if she has all of her favorite toys.',
        age: '2 months',
        inoculations: ['none'],
        diseases: ['none'],
        parasites: ['none'],
      },
      {   
        id: 3,
        name: 'Woody',
        img: '../../assets/images/pets-woody.png',
        type: 'dog',
        breed: 'Labrador',
        description: 'Jennifer is a sweet 2 months old Labrador that is patiently waiting to find a new forever home. This girl really enjoys being able to go outside to run and play, but won\'t hesitate to play up a storm in the house if she has all of her favorite toys.',
        age: '2 months',
        inoculations: ['none'],
        diseases: ['none'],
        parasites: ['none'],
      },
      {   
        id: 4,
        name: 'Woody1',
        img: '../../assets/images/pets-scarlet.png',
        type: 'dog',
        breed: 'Labrador',
        description: 'Jennifer is a sweet 2 months old Labrador that is patiently waiting to find a new forever home. This girl really enjoys being able to go outside to run and play, but won\'t hesitate to play up a storm in the house if she has all of her favorite toys.',
        age: '2 months',
        inoculations: ['none'],
        diseases: ['none'],
        parasites: ['none'],
      },
      {   
        id: 5,
        name: 'Woody2',
        img: '../../assets/images/pets-freddie.png',
        type: 'dog',
        breed: 'Labrador',
        description: 'Jennifer is a sweet 2 months old Labrador that is patiently waiting to find a new forever home. This girl really enjoys being able to go outside to run and play, but won\'t hesitate to play up a storm in the house if she has all of her favorite toys.',
        age: '2 months',
        inoculations: ['none'],
        diseases: ['none'],
        parasites: ['none'],
      },
      {   
        id: 6,
        name: 'Woody3',
        img: '../../assets/images/pets-charly.png',
        type: 'dog',
        breed: 'Labrador',
        description: 'Jennifer is a sweet 2 months old Labrador that is patiently waiting to find a new forever home. This girl really enjoys being able to go outside to run and play, but won\'t hesitate to play up a storm in the house if she has all of her favorite toys.',
        age: '2 months',
        inoculations: ['none'],
        diseases: ['none'],
        parasites: ['none'],
      }
];

export default data;